name: MyFirstWorkflow
on: 
 push:
  branches: main
 pull_request:
  branches: main
jobs:
 build:
   runs-on: ${{matrix.os}}
   strategy:
     matrix:
       os: [ubuntu-latest, macOS-latest, windows-latest]
   steps:
     - name: Checking the code
       uses: actions/checkout@v4
     - name: Language Setup
       uses: actions/setup-node@v4
       with:
          node-version: 18
     - run: npm ci
     
     - name: Set up Docker
       uses: docker/setup-docker@v2

     - name: Build and push Docker image
       uses: docker/build-push-action@v2
       with:
        context: .
        push: true
        tags: |
          docker.io/imanagha/test:latest
          docker.io/imanagha/test:v1
     - name: Check Docker version
       run: docker --version
     - name: Build Docker image
       run: |
           docker build -f src/Dockerfile -t docker.io/imanagha/test:v1 -t docker.io/imanagha/test:latest .
      
  
     
  
