name: MyFirstWorkflow
on: 
 push:
  branches: main
 pull_request:
  branches: main
jobs:
 build:
   runs-on: windows-latest
   steps:
     - name: Checking the code
       uses: action/checkout@v4
     - name: Language Setup
       uses: actions/setup-node@v4
       with:
          node-version: 18
     - run: npm ci
     - run: npm test
  
     
  
