name: MyFirstWorkflow
on: 
 push:
  branches: main
 pull_request:
  branches: main
jobs:
 build:
   runs-on: windows-latest
   steps:
     - name: Checking the code
       uses: action/checkout@v4

     
  
